#include "ops.h"
#include "../op_kernel/tq_fused_decode_tiling.h"

#include <acl/acl.h>
#include <torch_npu/csrc/core/npu/NPUStream.h>

#include <cstdint>
#include <cstdio>

// The aclrtlaunch wrapper is auto-generated by the CCE compiler.
// IMPORTANT: the generated stub has NO l2Ctrl parameter — its signature is:
//   uint32_t aclrtlaunch_...(uint32_t blockDim, void* stream,
//       void* queryRot, void* kvCache, void* blockTable,
//       void* seqLens, void* centroidsTiling, void* output)
// Adding an extra l2Ctrl parameter shifts all args by one register on aarch64.
extern "C" uint32_t aclrtlaunch_tq_fused_decode_kernel(
    uint32_t blockDim, void* stream,
    void* queryRot, void* kvCache, void* blockTable,
    void* seqLens, void* centroidsTiling, void* output);

namespace ascend_kernel {

// Centroids: 16 float32 = 64 bytes. Must match CENTROID_TABLE_SIZE in kernel.
constexpr int64_t kCentroidBytes = 16 * sizeof(float);  // 64
// Tiling: 72 bytes struct, padded to 96 for 32-byte alignment.
constexpr int64_t kTilingBufAligned =
    ((sizeof(TqFusedDecodeTilingData) + 31) / 32) * 32;  // 96

torch::Tensor tq_fused_decode_torch(
    const torch::Tensor& query_rot,
    const torch::Tensor& kv_cache,
    const torch::Tensor& block_table,
    const torch::Tensor& seq_lens,
    const torch::Tensor& centroids,
    double sm_scale,
    int64_t mse_bytes,
    int64_t key_packed_size,
    int64_t val_data_bytes,
    int64_t head_dim,
    int64_t block_size,
    bool norm_correction) {
    auto q = query_rot.contiguous();
    auto kv = kv_cache.contiguous();
    auto bt = block_table.contiguous().to(q.device(), at::kInt);
    auto sl = seq_lens.contiguous().to(q.device(), at::kInt);

    // Compute tiling BEFORE launching (needed for combined buffer)
    TqFusedDecodeTilingData tiling;
    memset(&tiling, 0, sizeof(tiling));
    tiling.batchSize = static_cast<uint32_t>(q.size(0));
    tiling.numQueryHeads = static_cast<uint32_t>(q.size(1));
    tiling.numKvHeads = static_cast<uint32_t>(kv.size(2));
    tiling.gqaRatio = static_cast<uint32_t>(q.size(1) / kv.size(2));
    tiling.gridSize = static_cast<uint32_t>(q.size(0) * q.size(1));
    tiling.blockSize = static_cast<uint32_t>(block_size);
    tiling.headDim = static_cast<uint32_t>(head_dim);
    tiling.mseBytes = static_cast<uint32_t>(mse_bytes);
    tiling.keyPackedSize = static_cast<uint32_t>(key_packed_size);
    tiling.valDataBytes = static_cast<uint32_t>(val_data_bytes);
    tiling.slotSize = static_cast<uint32_t>(kv.size(3));
    tiling.maxBlocksPerSeq = static_cast<uint32_t>(bt.size(1));
    tiling.blockStride = static_cast<uint64_t>(block_size) * kv.size(2) * kv.size(3);
    tiling.slotStride = static_cast<uint64_t>(kv.size(2)) * kv.size(3);
    tiling.normCorrection = norm_correction ? 1u : 0u;
    tiling.smScale = static_cast<float>(sm_scale);

    uint32_t blockDim = tiling.gridSize;
    if (blockDim == 0) blockDim = 1;

    // ---- Build combined tiling+centroids buffer ----
    // Layout: [tiling: 96B] [centroids: 64B] = 160B
    constexpr int64_t kCombinedBytes = kTilingBufAligned + kCentroidBytes;  // 160

    // Create CPU buffer
    auto combinedCpu = torch::empty({kCombinedBytes}, at::kByte);
    auto* combinedPtr = combinedCpu.data_ptr<uint8_t>();

    // TILING FIRST (offset 0, 96 bytes), then centroids (offset 96, 64 bytes)
    memcpy(combinedPtr, &tiling, sizeof(tiling));

    // Copy centroids as float32 after tiling
    auto ctCpu = centroids.to(at::kCPU).to(at::kFloat).contiguous();
    memcpy(combinedPtr + kTilingBufAligned, ctCpu.data_ptr<float>(), kCentroidBytes);

    // Allocate device memory directly via aclrtMalloc (bypasses PyTorch allocator)
    void* combinedDevPtr = nullptr;
    aclError allocRet = aclrtMalloc(&combinedDevPtr, kCombinedBytes, ACL_MEM_MALLOC_NORMAL_ONLY);
    if (allocRet != ACL_SUCCESS) {
        printf("[TQ] ERROR aclrtMalloc failed: %d\n", (int)allocRet);
        return at::zeros({q.size(0), q.size(1), q.size(2)}, q.options().dtype(at::kHalf));
    }
    aclError memcpyRet = aclrtMemcpy(
        combinedDevPtr, kCombinedBytes,
        combinedCpu.data_ptr(), kCombinedBytes,
        ACL_MEMCPY_HOST_TO_DEVICE);

    int64_t B = q.size(0), Hq = q.size(1), D = q.size(2);
    auto output = at::empty({B, Hq, D}, q.options().dtype(at::kHalf));
    auto aclStream = c10_npu::getCurrentNPUStream().stream(false);

    aclrtlaunch_tq_fused_decode_kernel(
        blockDim, aclStream,
        q.data_ptr(), kv.data_ptr(), bt.data_ptr(),
        sl.data_ptr(), combinedDevPtr, output.data_ptr());

    aclError aclRet = aclrtSynchronizeStream(aclStream);
    if (aclRet != ACL_SUCCESS) {
        printf("[TQ] ERROR sync=%d B=%lld Hq=%lld seq0=%d slotSize=%d blockStride=%lu\n",
               (int)aclRet, (long long)B, (long long)Hq,
               (int)sl.item<int32_t>(), tiling.slotSize,
               (unsigned long)tiling.blockStride);
        fflush(stdout);
    }

    // Free the raw device memory
    aclrtFree(combinedDevPtr);

    return output;
}

} // namespace ascend_kernel
