#include "ops.h"
#include "../op_kernel/tq_fused_decode_tiling.h"

#include <acl/acl.h>
#include <torch_npu/csrc/core/npu/NPUStream.h>

#include <cstdint>
#include <cstdio>

// The aclrtlaunch wrapper is auto-generated by the CCE compiler from the
// kernel's __aicore__ function. We reduced to 6 GM_ADDR args because the
// CCE-generated wrapper did not reliably pass a 7th argument (the tiling
// data arrived as garbage 0xD160D160 on device).
//
// Workaround: tiling data is packed after centroids in a combined buffer.
// Layout: [centroids: 16 float32 = 64B] [tiling: 24 int32 = 96B] = 160B total.
// The kernel reads centroids from offset 0 and tiling from offset 64.
extern "C" void aclrtlaunch_tq_fused_decode_kernel(
    uint32_t blockDim, void* l2Ctrl, aclrtStream stream,
    void* queryRot, void* kvCache, void* blockTable,
    void* seqLens, void* centroidsTiling, void* output);

namespace ascend_kernel {

// Centroids: 16 float32 = 64 bytes. Must match CENTROID_TABLE_SIZE in kernel.
constexpr int64_t kCentroidBytes = 16 * sizeof(float);  // 64

torch::Tensor tq_fused_decode_torch(
    const torch::Tensor& query_rot,
    const torch::Tensor& kv_cache,
    const torch::Tensor& block_table,
    const torch::Tensor& seq_lens,
    const torch::Tensor& centroids,
    double sm_scale,
    int64_t mse_bytes,
    int64_t key_packed_size,
    int64_t val_data_bytes,
    int64_t head_dim,
    int64_t block_size,
    bool norm_correction) {
    auto q = query_rot.contiguous();
    auto kv = kv_cache.contiguous();
    auto bt = block_table.contiguous().to(q.device(), at::kInt);
    auto sl = seq_lens.contiguous().to(q.device(), at::kInt);

    // Compute tiling BEFORE launching (needed for combined buffer)
    TqFusedDecodeTilingData tiling;
    memset(&tiling, 0, sizeof(tiling));
    tiling.batchSize = static_cast<uint32_t>(q.size(0));
    tiling.numQueryHeads = static_cast<uint32_t>(q.size(1));
    tiling.numKvHeads = static_cast<uint32_t>(kv.size(2));
    tiling.gqaRatio = static_cast<uint32_t>(q.size(1) / kv.size(2));
    tiling.gridSize = static_cast<uint32_t>(q.size(0) * q.size(1));
    tiling.blockSize = static_cast<uint32_t>(block_size);
    tiling.headDim = static_cast<uint32_t>(head_dim);
    tiling.mseBytes = static_cast<uint32_t>(mse_bytes);
    tiling.keyPackedSize = static_cast<uint32_t>(key_packed_size);
    tiling.valDataBytes = static_cast<uint32_t>(val_data_bytes);
    tiling.slotSize = static_cast<uint32_t>(kv.size(3));
    tiling.maxBlocksPerSeq = static_cast<uint32_t>(bt.size(1));
    tiling.blockStride = static_cast<uint64_t>(block_size) * kv.size(2) * kv.size(3);
    tiling.slotStride = static_cast<uint64_t>(kv.size(2)) * kv.size(3);
    tiling.normCorrection = norm_correction ? 1u : 0u;
    tiling.smScale = static_cast<float>(sm_scale);

    uint32_t blockDim = tiling.gridSize;
    if (blockDim == 0) blockDim = 1;

    // ---- Build combined centroids+tiling buffer ----
    // Layout: [centroids: 16 float32 = 64B] [tiling: ceil72to32 = 96B] = 160B
    constexpr int64_t kTilingBufAligned =
        ((sizeof(TqFusedDecodeTilingData) + 31) / 32) * 32;  // 96
    constexpr int64_t kCombinedBytes = kCentroidBytes + kTilingBufAligned;  // 160

    // Create CPU buffer
    auto combinedCpu = torch::empty({kCombinedBytes}, at::kByte);
    auto* combinedPtr = combinedCpu.data_ptr<uint8_t>();

    // Copy centroids as float32 (convert from whatever dtype the caller uses)
    auto ctCpu = centroids.to(at::kCPU).to(at::kFloat).contiguous();
    memcpy(combinedPtr, ctCpu.data_ptr<float>(), kCentroidBytes);

    // Copy tiling after centroids
    memcpy(combinedPtr + kCentroidBytes, &tiling, sizeof(tiling));

    // Transfer to NPU via synchronous aclrtMemcpy
    auto combinedTensor = torch::empty({kCombinedBytes}, q.options().dtype(at::kByte));
    aclError memcpyRet = aclrtMemcpy(
        combinedTensor.data_ptr(), kCombinedBytes,
        combinedCpu.data_ptr(), kCombinedBytes,
        ACL_MEMCPY_HOST_TO_DEVICE);

    // Diagnostics
    printf("[TQ-HOST] q: dev=%d dtype=%d shape=[%ld,%ld,%ld]\n",
           static_cast<int>(q.device().type()),
           static_cast<int>(q.scalar_type()),
           q.size(0), q.size(1), q.size(2));
    printf("[TQ-HOST] kv: dev=%d dtype=%d shape=[%ld,%ld,%ld,%ld]\n",
           static_cast<int>(kv.device().type()),
           static_cast<int>(kv.scalar_type()),
           kv.size(0), kv.size(1), kv.size(2), kv.size(3));
    printf("[TQ-HOST] ct: dtype=%d numel=%ld -> combined as fp32\n",
           static_cast<int>(centroids.scalar_type()),
           centroids.numel());
    printf("[TQ-HOST] combined ptr=%p memcpy_ret=%d\n",
           combinedTensor.data_ptr(), (int)memcpyRet);
    printf("[TQ-HOST] Launching blockDim=%d grid=%d B=%d Hq=%d Hk=%d "
           "headDim=%d blockSize=%d slotSize=%d blockStride=%lu slotStride=%lu\n",
           blockDim, tiling.gridSize, tiling.batchSize, tiling.numQueryHeads,
           tiling.numKvHeads, tiling.headDim, tiling.blockSize, tiling.slotSize,
           (unsigned long)tiling.blockStride, (unsigned long)tiling.slotStride);
    fflush(stdout);

    // Output tensor (fp16, sentinel -42.0 for diagnostic)
    int64_t B = q.size(0), Hq = q.size(1), D = q.size(2);
    auto output = at::full({B, Hq, D}, -42.0f, q.options().dtype(at::kHalf));
    auto aclStream = c10_npu::getCurrentNPUStream().stream(true);

    // 6-argument kernel launch
    aclrtlaunch_tq_fused_decode_kernel(
        blockDim, nullptr, aclStream,
        q.data_ptr(), kv.data_ptr(), bt.data_ptr(),
        sl.data_ptr(), combinedTensor.data_ptr(), output.data_ptr());

    aclError aclRet = aclrtSynchronizeStream(aclStream);
    printf("[TQ-HOST] sync=%d output[0][0][0]=%f\n",
           (int)aclRet,
           static_cast<float>(output[0][0][0].item<at::Half>()));
    fflush(stdout);

    return output;
}

} // namespace ascend_kernel
