#include "ops.h"
#include "../op_kernel/tq_fused_decode_tiling.h"

#include <acl/acl.h>
#include <torch_npu/csrc/core/npu/NPUStream.h>

#include <cstdint>
#include <cstdio>

// The aclrtlaunch wrapper is auto-generated by the CCE compiler.
// IMPORTANT: the generated stub has NO l2Ctrl parameter — its signature is:
//   uint32_t aclrtlaunch_...(uint32_t blockDim, void* stream,
//       void* queryRot, void* kvCache, void* blockTable,
//       void* seqLens, void* centroidsTiling, void* output)
// Adding an extra l2Ctrl parameter shifts all args by one register on aarch64.
extern "C" uint32_t aclrtlaunch_tq_fused_decode_kernel(
    uint32_t blockDim, void* stream,
    void* queryRot, void* kvCache, void* blockTable,
    void* seqLens, void* centroidsTiling, void* output);

namespace ascend_kernel {

// Centroids: 16 float32 = 64 bytes. Must match CENTROID_TABLE_SIZE in kernel.
constexpr int64_t kCentroidBytes = 16 * sizeof(float);  // 64
// Tiling: 72 bytes struct, padded to 96 for 32-byte alignment.
constexpr int64_t kTilingBufAligned =
    ((sizeof(TqFusedDecodeTilingData) + 31) / 32) * 32;  // 96

torch::Tensor tq_fused_decode_torch(
    const torch::Tensor& query_rot,
    const torch::Tensor& kv_cache,
    const torch::Tensor& block_table,
    const torch::Tensor& seq_lens,
    const torch::Tensor& centroids,
    double sm_scale,
    int64_t mse_bytes,
    int64_t key_packed_size,
    int64_t val_data_bytes,
    int64_t head_dim,
    int64_t block_size,
    bool norm_correction) {
    auto q = query_rot.contiguous();
    auto kv = kv_cache.contiguous();
    auto bt = block_table.contiguous().to(q.device(), at::kInt);
    auto sl = seq_lens.contiguous().to(q.device(), at::kInt);

    // Compute tiling BEFORE launching (needed for combined buffer)
    TqFusedDecodeTilingData tiling;
    memset(&tiling, 0, sizeof(tiling));
    tiling.batchSize = static_cast<uint32_t>(q.size(0));
    tiling.numQueryHeads = static_cast<uint32_t>(q.size(1));
    tiling.numKvHeads = static_cast<uint32_t>(kv.size(2));
    tiling.gqaRatio = static_cast<uint32_t>(q.size(1) / kv.size(2));
    tiling.gridSize = static_cast<uint32_t>(q.size(0) * q.size(1));
    tiling.blockSize = static_cast<uint32_t>(block_size);
    tiling.headDim = static_cast<uint32_t>(head_dim);
    tiling.mseBytes = static_cast<uint32_t>(mse_bytes);
    tiling.keyPackedSize = static_cast<uint32_t>(key_packed_size);
    tiling.valDataBytes = static_cast<uint32_t>(val_data_bytes);
    tiling.slotSize = static_cast<uint32_t>(kv.size(3));
    tiling.maxBlocksPerSeq = static_cast<uint32_t>(bt.size(1));
    tiling.blockStride = static_cast<uint64_t>(block_size) * kv.size(2) * kv.size(3);
    tiling.slotStride = static_cast<uint64_t>(kv.size(2)) * kv.size(3);
    tiling.normCorrection = norm_correction ? 1u : 0u;
    tiling.smScale = static_cast<float>(sm_scale);

    uint32_t blockDim = tiling.gridSize;
    if (blockDim == 0) blockDim = 1;

    // ---- Build combined tiling+centroids buffer ----
    // Layout: [tiling: 96B] [centroids: 64B] = 160B
    constexpr int64_t kCombinedBytes = kTilingBufAligned + kCentroidBytes;  // 160

    // Create CPU buffer
    auto combinedCpu = torch::empty({kCombinedBytes}, at::kByte);
    auto* combinedPtr = combinedCpu.data_ptr<uint8_t>();

    // TILING FIRST (offset 0, 96 bytes), then centroids (offset 96, 64 bytes)
    memcpy(combinedPtr, &tiling, sizeof(tiling));

    // Copy centroids as float32 after tiling
    auto ctCpu = centroids.to(at::kCPU).to(at::kFloat).contiguous();
    memcpy(combinedPtr + kTilingBufAligned, ctCpu.data_ptr<float>(), kCentroidBytes);

    // Allocate device memory directly via aclrtMalloc (bypasses PyTorch allocator)
    void* combinedDevPtr = nullptr;
    aclError allocRet = aclrtMalloc(&combinedDevPtr, kCombinedBytes, ACL_MEM_MALLOC_NORMAL_ONLY);
    aclError memcpyRet = aclrtMemcpy(
        combinedDevPtr, kCombinedBytes,
        combinedCpu.data_ptr(), kCombinedBytes,
        ACL_MEMCPY_HOST_TO_DEVICE);

    // Readback verification
    uint8_t readback[96];
    aclError rbRet = aclrtMemcpy(readback, 96, combinedDevPtr, 96, ACL_MEMCPY_DEVICE_TO_HOST);
    auto* rbp = reinterpret_cast<int32_t*>(readback);
    auto* htp = reinterpret_cast<int32_t*>(combinedPtr);
    printf("[TQ-HOST] combined dev=%p alloc=%d memcpy=%d rb=%d\n",
           combinedDevPtr, (int)allocRet, (int)memcpyRet, (int)rbRet);
    printf("[TQ-HOST] host:");
    for (int i = 0; i < 6; i++) printf(" %08x", static_cast<uint32_t>(htp[i]));
    printf("\n[TQ-HOST] npu :");
    for (int i = 0; i < 6; i++) printf(" %08x", static_cast<uint32_t>(rbp[i]));
    bool match = (memcmp(readback, combinedPtr, 72) == 0);
    printf("\n[TQ-HOST] match=%s\n", match ? "YES" : "NO");
    printf("[TQ-HOST] Launching blockDim=%d grid=%d B=%d Hq=%d Hk=%d "
           "headDim=%d blockSize=%d slotSize=%d blockStride=%lu slotStride=%lu\n",
           blockDim, tiling.gridSize, tiling.batchSize, tiling.numQueryHeads,
           tiling.numKvHeads, tiling.headDim, tiling.blockSize, tiling.slotSize,
           (unsigned long)tiling.blockStride, (unsigned long)tiling.slotStride);
    fflush(stdout);

    // Output tensor (fp16, sentinel -42.0 for diagnostic)
    int64_t B = q.size(0), Hq = q.size(1), D = q.size(2);
    auto output = at::full({B, Hq, D}, -42.0f, q.options().dtype(at::kHalf));
    auto aclStream = c10_npu::getCurrentNPUStream().stream(false);

    // 6-argument kernel launch — no l2Ctrl, matches generated stub exactly
    aclrtlaunch_tq_fused_decode_kernel(
        blockDim, aclStream,
        q.data_ptr(), kv.data_ptr(), bt.data_ptr(),
        sl.data_ptr(), combinedDevPtr, output.data_ptr());

    aclError aclRet = aclrtSynchronizeStream(aclStream);
    printf("[TQ-HOST] sync=%d output[0][0][0]=%f\n",
           (int)aclRet,
           static_cast<float>(output[0][0][0].item<at::Half>()));
    fflush(stdout);

    // Free the raw device memory
    aclrtFree(combinedDevPtr);

    return output;
}

} // namespace ascend_kernel
